# @file publish-release.yml
#
# A Github workflow that publishes all crates in a repository to crates.io and creates a release on
# GitHub.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: Publish Release

on:
  workflow_dispatch:

jobs:
  validate_branch:
    name: Validate Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Validate Branch
        run: |
          if [ "${GITHUB_REF}" != "refs/heads/main" ]; then
              echo "This workflow can only be run on the main branch."
              exit 1
          fi

  release:
    name: Release
    needs: validate_branch
    uses: microsoft/mu_devops/.github/workflows/ReleaseWorkflow.yml@main
    secrets:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    permissions:
      contents: write
      actions: read
